/**
 * Gamer One API Documentation
 * Welcome to the Official Gamer One API documentation.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: developer@gamerone.gg
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CurrentlyPlaying } from './currentlyPlaying';
import { LayoutSettings } from './layoutSettings';
import { Product } from './product';
import { SocialNetwork } from './socialNetwork';
import { Sponsor } from './sponsor';
import { User } from './user';
import { UserType } from './userType';

export interface Profile {
  user: User;
  /**
   * The users social network accounts
   */
  networks: Array<SocialNetwork>;
  /**
   * Collections of sponsors/endorsements the user has, if applicable.
   */
  sponsors: Array<Sponsor>;
  type: UserType;
  products: Array<Product>;
  currentlyPlaying: CurrentlyPlaying;
  layout: LayoutSettings;
}
